# =================================================
# == Argo CD Configuration Application
# =================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd # Argo CD should be managed in its own namespace
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 8.1.2 # Must match the version installed by the bootstrap script
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: argoproj.io
    kind: Application
    jsonPointers:
    - /spec/source
  helm:
    values: |
      configs:
        params:
          "server.insecure": "true"
        cm:
          url: https://argocd.dossware.com