apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
