# =================================================
# == Redis Application
# =================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd # Argo CD Application definition lives in argocd namespace
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 19.6.1 # Using a specific stable version
  destination:
    server: https://kubernetes.default.svc
    namespace: data-services # Actual Redis resources will be in 'data-services' namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true