# ===================================================================
# == Declarative App Stack for dossware.com (Traefik Version)
# == This is the GitOps file. It defines all user-facing applications
# == and the configuration for Argo CD itself.
# ==
# == To use:
# == 1. Run the bootstrap.sh script first.
# == 2. Place this file in a Git repository.
# == 3. Create one final "root" app in Argo CD UI that points to this file.
# ===================================================================

# =================================================
# == 1. Argo CD Configuration Application
# == This app manages Argo CD's own settings, like its Ingress.
# == NOTE: This was moved from the bootstrap script to here to be managed by GitOps.
# =================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # This app configures Argo CD itself
  name: argocd-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 8.1.2 # Must match the version installed by the bootstrap script
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # ADDED: This might help with resources that go OutOfSync but are otherwise healthy.
    # It tells Argo CD to only apply changes if the resource is currently OutOfSync.
    # applyOutOfSyncOnly: true # This option is for specific situations and might not be suitable here.
                              # Keeping prune and selfHeal is generally sufficient.
  # Ignore differences to avoid sync loops when managing itself
  ignoreDifferences:
  - group: argoproj.io
    kind: Application
    jsonPointers:
    - /spec/source
  helm:
    values: |
      # Apply all the proxy-related fixes and Ingress config
      configs:
        params:
          "server.insecure": "true"
        cm:
          url: https://argocd.dossware.com

---

# =================================================
# == 2. Prometheus + Grafana Application
# =================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 58.1.0 # Using a specific stable version
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    # ADDED: This might help ensure all resources are reconciled, even if already created.
    # applyOutOfSyncOnly: true # This option is for specific situations and might not be suitable here.
                              # Keeping prune and selfHeal is generally sufficient.
  # --- MODIFIED: Expanded ignoreDifferences to fix OutOfSync issue for common Helm chart fields ---
  ignoreDifferences:
  - group: "*"
    kind: "*"
    jsonPointers:
    - /metadata/labels
    - /metadata/annotations # Added to ignore changes in annotations
    - /metadata/creationTimestamp # Added to ignore differences in creation timestamp
  helm:
    values: |
      grafana:
        # --- Ingress Configuration for Grafana ---
        ingress:
          enabled: true
          ingressClassName: traefik
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hosts:
            - "grafana.dossware.com"
          tls:
            - secretName: grafana-dossware-com-tls
              hosts:
                - "grafana.dossware.com"
        # --- Grafana config to handle proxying correctly ---
        grafana.ini:
          server:
            root_url: https://grafana.dossware.com
            serve_from_sub_path: false
        # --- Persistence for Grafana ---
        persistence:
          enabled: true
          type: pvc
          storageClassName: "local-path" # K3s default storage class
          accessModes:
            - ReadWriteOnce
          size: 5Gi

      prometheus:
        # --- Persistence for Prometheus ---
        prometheusSpec:
          storageSpec:
            volumeClaimTemplate:
              spec:
                storageClassName: "local-path" # K3s default storage class
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 20Gi
---

# =================================================
# == 3. Redis Application
# =================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 19.6.1 # Using a specific stable version
  destination:
    server: https://kubernetes.default.svc
    namespace: data-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

# =================================================
# == 4. RabbitMQ Application
# =================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: 15.2.0 # Using a specific stable version
  destination:
    server: https://kubernetes.default.svc
    namespace: data-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  helm:
    values: |
      auth:
        username: "myuser"
        password: "mypassword"
        erlangCookie: "mysecretcookie"
      ingress:
        enabled: true
        ingressClassName: traefik
        hostname: "rabbitmq.dossware.com"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        tls: true
        extraTls:
          - hosts:
              - "rabbitmq.dossware.com"
            secretName: rabbitmq-dossware-com-tls
      # --- ADDED: Disable readiness/liveness probes to avoid 401 error ---
      # This is a workaround for the 401 error if probes cannot authenticate.
      # In a production environment, you would configure probes correctly with auth.
      livenessProbe:
        enabled: false
      readinessProbe:
        enabled: false