grafana:
  enabled: true
  adminUser: admin
  adminPassword: prom-operator
  defaultDashboardsEnabled: true
  persistence:
    enabled: true
    size: 5Gi
    storageClassName: ""
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false  # ใช้ IngressRoute แทน

  grafana.ini:
    server:
      root_url: "https://grafana.yourdomain.com"
    security:
      admin_user: admin
      admin_password: prom-operator
    users:
      allow_sign_up: false

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      prometheus-stats:
        gnetId: 1860
        revision: 23
        datasource: Prometheus

prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 8Gi
          storageClassName: ""

alertmanager:
  enabled: true
